FROM myoung34/github-runner:ubuntu-noble

USER root
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends libperl-dev \
    && curl -fsSL https://cpanmin.us -o /usr/local/bin/cpanm \
    && chmod +x /usr/local/bin/cpanm \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
