name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: self-hosted
    env:
      DEBIAN_FRONTEND: noninteractive

    strategy:
      matrix:
        perl-version: [ '5.32', '5.36', '5.38', '5.40' ]

    steps:
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          build-essential curl ca-certificates git libffi-dev

    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Perl Dependencies
      run: |
        cpanm --notest FFI::Platypus

    - name: Build and Test Module
      run: |
        perl Makefile.PL
        make
        make test
